on:
  workflow_call:
    outputs:
      platforms:
        description: "The platforms the docker image will be built for"
        value: ${{ jobs.docker-setup-and-login.outputs.platforms }}

jobs:
  docker-setup-and-login:
    runs-on: ubuntu-latest
    outputs:
        platforms: ${{ steps.buildx.outputs.platforms }}

    steps:
      - # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm/v7,linux/arm64
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}